### ISSUE TITLE
Error: error archiving file: could not archive missing file:

### ISSUE THREAD

**Issue by ctopinka** [sah-shatrujeet/infra_spot_fleet_terraform#1]
`terraform plan` gives

```

Error: error archiving file: could not archive missing file: interruption.py

  on ../modules/archive/main.tf line 1, in data "archive_file" "zip":
   1: data "archive_file" "zip" {



Error: error archiving file: could not archive missing file: od_running.py

  on ../modules/archive1/main.tf line 1, in data "archive_file" "zip1":
   1: data "archive_file" "zip1" {


```

**Comment by ctopinka** [comment]
Looks like it was switched to use .tpl templates? Is there a need for zip still?

**Comment by ctopinka** [comment]
This is apparently an outcome of attempting to ugrade tf version.

**Comment by shatrujeet95** [comment]
> `terraform plan` gives
> 
> ```
> 
> Error: error archiving file: could not archive missing file: interruption.py
> 
>   on ../modules/archive/main.tf line 1, in data "archive_file" "zip":
>    1: data "archive_file" "zip" {
> 
> 
> 
> Error: error archiving file: could not archive missing file: od_running.py
> 
>   on ../modules/archive1/main.tf line 1, in data "archive_file" "zip1":
>    1: data "archive_file" "zip1" {
> ```

Although you have closed this ticket, but let me know If you are still facing the issue. I will be happy to help.
